Repository jupyter/nbdime, pull requests merged in 2023-10, with the labels that each got.

#696 Improve diff view
  nbdime/webapp/templates/diff.html
  nbdime/webapp/templates/difftool.html
  packages/labextension/package.json
  packages/labextension/src/widget.ts
  packages/labextension/style/index.css
  packages/nbdime/src/common/mergeview.ts
  packages/nbdime/src/diff/widget/cell.ts
  packages/nbdime/src/styles/common.css
  packages/nbdime/src/styles/diff.css
  packages/webapp/src/app/common.css
  packages/webapp/src/app/diff.css
  tsconfig.json
  ui-tests/tests/nbdime-diff-test1.spec.ts-snapshots/diff-test1-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-diff-test1.spec.ts-snapshots/diff-test1-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-diff-test2.spec.ts-snapshots/diff-test2-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-diff-test2.spec.ts-snapshots/diff-test2-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-diff-test3.spec.ts-snapshots/diff-test3-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-diff-test3.spec.ts-snapshots/diff-test3-take-a-snapshot-at-opening-1-win32.png
Labels: bug

#702 Switch from hub to gh CLI
  .github/workflows/update-integration-tests.yml
Labels: maintenance

#701 Restore collapsers
  package-lock.json
  package.json
  packages/nbdime/src/common/mergeview.ts
  packages/nbdime/src/styles/diff.css
  packages/webapp/package.json
  ui-tests/data/merge_test4/center.ipynb
  ui-tests/data/merge_test4/left.ipynb
  ui-tests/data/merge_test4/right.ipynb
  ui-tests/package-lock.json
  ui-tests/playwright.config.js
  ui-tests/tests/nbdime-diff-test3.spec.ts-snapshots/diff-test3-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-diff-test3.spec.ts-snapshots/diff-test3-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-central-version-for-conflict-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-central-version-for-conflict-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-left-version-for-conflict-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-left-version-for-conflict-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-right-version-for-conflict-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-right-version-for-conflict-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-central-version-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-central-version-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-left-version-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-left-version-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-right-version-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-right-version-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test4.spec.ts
  ui-tests/tests/nbdime-merge-test4.spec.ts-snapshots/merge-test4-should-synchronize-the-collapse-status-between-editor-1-linux.png
  ui-tests/tests/nbdime-merge-test4.spec.ts-snapshots/merge-test4-should-synchronize-the-collapse-status-between-editor-1-win32.png
Labels: enhancement

#705 Support hiding base editor
  nbdime/args.py
  nbdime/config.py
  nbdime/webapp/nbdimeserver.py
  packages/nbdime/src/common/basepanel.ts
  packages/nbdime/src/common/interfaces.ts
  packages/nbdime/src/common/mergeview.ts
  packages/nbdime/src/diff/widget/cell.ts
  packages/nbdime/src/diff/widget/metadata.ts
  packages/nbdime/src/diff/widget/notebook.ts
  packages/nbdime/src/diff/widget/output.ts
  packages/nbdime/src/merge/widget/cell.ts
  packages/nbdime/src/merge/widget/metadata.ts
  packages/nbdime/src/merge/widget/notebook.ts
  packages/nbdime/src/merge/widget/output.ts
  packages/nbdime/src/styles/common.css
  packages/webapp/src/app/merge.css
  packages/webapp/src/app/merge.ts
  ui-tests/tests/nbdime-merge-test1.spec.ts
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/3-panels-view-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/3-panels-view-1-win32.png
  ui-tests/tests/nbdime-merge-test3.spec.ts
Labels: enhancement

#707 Make collapseIdentical margin configurable
  nbdime/args.py
  nbdime/tests/test_server_extension.py
  nbdime/webapp/nbdimeserver.py
  package.json
  packages/nbdime/src/common/basepanel.ts
  packages/nbdime/src/common/interfaces.ts
  packages/nbdime/src/common/mergeview.ts
  packages/nbdime/src/diff/widget/cell.ts
  packages/nbdime/src/diff/widget/metadata.ts
  packages/nbdime/src/diff/widget/notebook.ts
  packages/nbdime/src/diff/widget/output.ts
  packages/nbdime/src/merge/widget/cell.ts
  packages/nbdime/src/merge/widget/metadata.ts
  packages/nbdime/src/merge/widget/notebook.ts
  packages/webapp/src/app/diff.ts
  packages/webapp/src/app/merge.ts
Labels: enhancement

#708 Upgrade devdependencies and clean up the configuration
  lerna.json
  package-lock.json
  package.json
  packages/nbdime/tslint.json
  packages/webapp/tslint.json
Labels: maintenance

#706 Improve `findAlignedLines`
  packages/nbdime/src/common/mergeview.ts
  ui-tests/data/merge_test5/center.ipynb
  ui-tests/data/merge_test5/left.ipynb
  ui-tests/data/merge_test5/right.ipynb
  ui-tests/tests/nbdime-merge-test1.spec.ts
  ui-tests/tests/nbdime-merge-test2.spec.ts
  ui-tests/tests/nbdime-merge-test5.spec.ts
  ui-tests/tests/nbdime-merge-test5.spec.ts-snapshots/merge-test5-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test5.spec.ts-snapshots/merge-test5-take-a-snapshot-at-opening-1-win32.png
Labels: bug

#600 Chore: use jupyter packaging
  .github/workflows/tests.yml
  MANIFEST.in
  nbdime/_version.py
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  setupbase.py
Labels: maintenance

#711 Apply post-mortem review comments
  .github/workflows/tests.yml
  nbdime/args.py
  nbdime/config.py
  nbdime/webapp/nbmergeweb.py
  package-lock.json
  package.json
  packages/nbdime/src/common/mergeview.ts
  ui-tests/tests/nbdime-merge-test1.spec.ts
Labels: bug

#715 Add CSS files in nbdime package
  packages/nbdime/package.json
Labels: bug

#717 Improve alignment
  packages/labextension/style/index.css
  packages/nbdime/src/styles/diff.css
  packages/webapp/src/app/diff.css
  ui-tests/tests/nbdime-diff-test1.spec.ts-snapshots/diff-test1-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-diff-test1.spec.ts-snapshots/diff-test1-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-diff-test2.spec.ts-snapshots/diff-test2-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-diff-test2.spec.ts-snapshots/diff-test2-take-a-snapshot-at-opening-1-win32.png
Labels: bug

#719 Do not collapse editor lines in single editor
  nbdime/webapp/templates/compare.html
  nbdime/webapp/templates/diff.html
  nbdime/webapp/templates/difftool.html
  nbdime/webapp/templates/merge.html
  nbdime/webapp/templates/mergetool.html
  packages/nbdime/src/common/mergeview.ts
  ui-tests/data/merge_test6/center.ipynb
  ui-tests/data/merge_test6/left.ipynb
  ui-tests/data/merge_test6/right.ipynb
  ui-tests/package-lock.json
  ui-tests/tests/nbdime-merge-test6.spec.ts
  ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-win32.png
Labels: bug

#709 Add translation for the frontend in Lab
  package-lock.json
  package.json
  packages/labextension/package.json
  packages/labextension/src/actions.ts
  packages/labextension/src/plugin.ts
  packages/labextension/src/widget.ts
  packages/nbdime/src/common/basepanel.ts
  packages/nbdime/src/common/collapsiblepanel.ts
  packages/nbdime/src/common/interfaces.ts
  packages/nbdime/src/common/mergeview.ts
  packages/nbdime/src/diff/widget/cell.ts
  packages/nbdime/src/diff/widget/metadata.ts
  packages/nbdime/src/diff/widget/notebook.ts
  packages/nbdime/src/diff/widget/output.ts
  packages/nbdime/src/merge/widget/cell.ts
  packages/nbdime/src/merge/widget/common.ts
  packages/nbdime/src/merge/widget/dragdrop.ts
  packages/nbdime/src/merge/widget/metadata.ts
  packages/nbdime/src/merge/widget/notebook.ts
  ui-tests/tests/nbdime-merge-test4.spec.ts
  ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-win32.png
Labels: enhancement

#725 Update test badge
  README.md
Labels: documentation

#710 Set up releaser
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  RELEASE.md
  docs/source/installing.rst
  docs/source/nodevenv.rst
  package-lock.json
  package.json
  packages/webapp/package.json
  pyproject.toml
  scripts/bump_version.py
Labels: maintenance

#723 Fix drag and drop
  packages/nbdime/src/common/dragpanel.css
  packages/nbdime/src/common/dragpanel.ts
  packages/nbdime/src/styles/diff.css
  packages/nbdime/src/styles/merge.css
  packages/nbdime/src/upstreaming/flexlayout.ts
  packages/nbdime/src/upstreaming/flexpanel.css
  packages/nbdime/src/upstreaming/flexpanel.ts
  packages/nbdime/test/src/common/flexpanel.spec.ts
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/3-panels-view-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/3-panels-view-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-central-version-for-conflict-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-central-version-for-conflict-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-left-version-for-conflict-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-left-version-for-conflict-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-right-version-for-conflict-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-choose-right-version-for-conflict-1-win32.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-central-version-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-central-version-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-left-version-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-left-version-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-right-version-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-choose-right-version-1-win32.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/merge-test2-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-merge-test4.spec.ts-snapshots/merge-test4-should-synchronize-the-collapse-status-between-editor-1-linux.png
  ui-tests/tests/nbdime-merge-test4.spec.ts-snapshots/merge-test4-should-synchronize-the-collapse-status-between-editor-1-win32.png
  ui-tests/tests/nbdime-merge-test5.spec.ts-snapshots/merge-test5-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test5.spec.ts-snapshots/merge-test5-take-a-snapshot-at-opening-1-win32.png
  ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-linux.png
  ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-win32.png
Labels: bug
